services:
  db:
    image: postgres:17.2-alpine
    container_name: mtgci-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
        - ./docker-mount/postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtgci-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db